name: "Set environment variables"
description: "Configures environment variables for a workflow"
runs:
  using: "composite"

  steps:
    - name: Read env file
      uses: buildjet/cache@v3
      id: env-cache
      with:
        path: gh.env-${{ github.sha }}
        key: env-cache
        restore-keys: env-cache-
    - name: Set Environment Variables
      uses: tw3lveparsecs/github-actions-setvars@latest
      with:
        envFilePath: gh.env-${{ github.sha }}
