export default function PrivacyAndPolicy() {
  return (
    <section className="bg-white py-10 sm:py-16 lg:py-24">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <h2 className="text-3xl font-bold leading-tight text-black sm:text-4xl lg:text-5xl">
          Privacy Policy
        </h2>
        <div className="mt-12 flow-root sm:mt-16">
          <div className="divide-gray--200 -my-9 divide-y">
            <div className="py-9">
              <p className="text-xl font-semibold text-black">Introduction</p>
              <p className="mt-3 text-base text-gray-600">Welcome to Timehuddle</p>
              <p className="mt-3 text-base text-gray-600">
                Timehuddle (“us”, “we”, or “our”) operates https://timehuddle.com (hereinafter referred to as
                “Service”).
              </p>
              <p className="mt-3 text-base text-gray-600">
                Our Privacy Policy governs your visit to https://timehuddle.com, and explains how we collect,
                safeguard and disclose information that results from your use of our Service.
              </p>
              <p className="mt-3 text-base text-gray-600">
                We use your data to provide and improve Service. By using Service, you agree to the collection
                and use of information in accordance with this policy. Unless otherwise defined in this
                Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms
                and Conditions.
              </p>
              <p className="mt-3 text-base text-gray-600">
                Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy
                Policy constitutes your agreement with us (“agreement”).
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Definitions</p>
              <p className="mt-3 text-base text-gray-600">
                SERVICE means the https://timehuddle.com website operated by Timehuddle.
              </p>
              <p className="mt-3 text-base text-gray-600">
                PERSONAL DATA means data about a living individual who can be identified from those data (or
                from those and other information either in our possession or likely to come into our
                possession).
              </p>
              <p className="mt-3 text-base text-gray-600">
                USAGE DATA is data collected automatically either generated by the use of Service or from
                Service infrastructure itself (for example, the duration of a page visit).
              </p>
              <p className="mt-3 text-base text-gray-600">
                COOKIES are small files stored on your device (computer or mobile device).
              </p>
              <p className="mt-3 text-base text-gray-600">
                DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with
                other persons) determines the purposes for which and the manner in which any personal data
                are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller
                of your data.
              </p>
              <p className="mt-3 text-base text-gray-600">
                DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the
                data on behalf of the Data Controller. We may use the services of various Service Providers in
                order to process your data more effectively.
              </p>
              <p className="mt-3 text-base text-gray-600">
                DATA SUBJECT is any living individual who is the subject of Personal Data.
              </p>
              <p className="mt-3 text-base text-gray-600">
                THE USER is the individual using our Service. The User corresponds to the Data Subject, who is
                the subject of Personal Data.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Information Collection and Use</p>
              <p className="mt-3 text-base text-gray-600">
                We collect several different types of information for various purposes to provide and improve
                our Service to you.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Definitions</p>
              <p className="text-md mt-3 font-semibold text-black">Personal Data</p>
              <p className="mt-3 text-base text-gray-600">
                While using our Service, we may ask you to provide us with certain personally identifiable
                information that can be used to contact or identify you (“Personal Data”). Personally
                identifiable information may include, but is not limited to:
              </p>
              <p className="text-md mt-3 font-semibold text-black">Cookies and Usage Data</p>
              <p className="mt-3 text-base text-gray-600">
                We may use your Personal Data to contact you with newsletters, marketing or promotional
                materials and other information that may be of interest to you. You may opt out of receiving
                any, or all, of these communications from us by following the unsubscribe link or by emailing
                at support@timehuddle.com.
              </p>
              <p className="text-md mt-3 font-semibold text-black">Usage Data</p>
              <p className="mt-3 text-base text-gray-600">
                We may also collect information that your browser sends whenever you visit our Service or when
                you access Service by or through a mobile device (“Usage Data”).
              </p>
              <p className="mt-3 text-base text-gray-600">
                This Usage Data may include information such as your computer's Internet Protocol address
                (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the
                time and date of your visit, the time spent on those pages, unique device identifiers and
                other diagnostic data.
              </p>
              <p className="mt-3 text-base text-gray-600">
                When you access Service with a mobile device, this Usage Data may include information such as
                the type of mobile device you use, your mobile device unique ID, the IP address of your mobile
                device, your mobile operating system, the type of mobile Internet browser you use, unique
                device identifiers and other diagnostic data.
              </p>
              <p className="text-md mt-3 font-semibold text-black">Tracking Cookies Data</p>
              <p className="mt-3 text-base text-gray-600">
                We use cookies and similar tracking technologies to track the activity on our Service and we
                hold certain information.
              </p>
              <p className="mt-3 text-base text-gray-600">
                Cookies are files with a small amount of data which may include an anonymous unique
                identifier. Cookies are sent to your browser from a website and stored on your device. Other
                tracking technologies are also used such as beacons, tags and scripts to collect and track
                information and to improve and analyze our Service.
              </p>
              <p className="mt-3 text-base text-gray-600">
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being
                sent. However, if you do not accept cookies, you may not be able to use some portions of our
                Service.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Use of Data</p>
              <p className="mt-3 text-base text-gray-600">
                Timehuddle uses the collected data for various purposes:
              </p>
              <ul className="mt-9 inline-flex flex-col items-start space-y-5 text-left">
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    to provide and maintain our Service;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    to notify you about changes to our Service;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    to allow you to participate in interactive features of our Service when you choose to do
                    so;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900"> to provide customer support; </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    to gather analysis or valuable information so that we can improve our Service;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    to monitor the usage of our Service;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    to detect, prevent and address technical issues;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    to fulfill any other purpose for which you provide it;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    to carry out our obligations and enforce our rights arising from any contracts entered
                    into between you and us, including for billing and collection;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    to provide you with notices about your account and/or subscription, including expiration
                    and renewal notices, email-instructions, etc.;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    to provide you with news, special offers and general information about other goods,
                    services and events which we offer that are similar to those that you have already
                    purchased or enquired about unless you have opted not to receive such information;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    in any other way we may describe when you provide the information;{" "}
                  </span>
                </li>
                <li className="inline-flex items-center space-x-2">
                  <svg
                    className="h-5 w-5 flex-shrink-0 text-indigo-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor">
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-base font-medium text-gray-900">
                    {" "}
                    for any other purpose with your consent.{" "}
                  </span>
                </li>
              </ul>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Retention of Data</p>
              <p className="mt-3 text-base text-gray-600">
                We will retain your Personal Data only for as long as is necessary for the purposes set out in
                this Privacy Policy. We will retain and use your Personal Data to the extent necessary to
                comply with our legal obligations (for example, if we are required to retain your data to
                comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
              </p>
              <p className="mt-3 text-base text-gray-600">
                We will also retain Usage Data for internal analysis purposes. Usage Data is generally
                retained for a shorter period, except when this data is used to strengthen the security or to
                improve the functionality of our Service, or we are legally obligated to retain this data for
                longer time periods.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Transfer of Data</p>
              <p className="mt-3 text-base text-gray-600">
                Your information, including Personal Data, may be transferred to – and maintained on –
                computers located outside of your state, province, country or other governmental jurisdiction
                where the data protection laws may differ from those of your jurisdiction.
              </p>
              <p className="mt-3 text-base text-gray-600">
                If you are located outside United States and choose to provide information to us, please note
                that we transfer the data, including Personal Data, to United States and process it there.
              </p>
              <p className="mt-3 text-base text-gray-600">
                Your consent to this Privacy Policy followed by your submission of such information represents
                your agreement to that transfer.
              </p>
              <p className="mt-3 text-base text-gray-600">
                Timehuddle will take all the steps reasonably necessary to ensure that your data is treated
                securely and in accordance with this Privacy Policy and no transfer of your Personal Data will
                take place to an organisation or a country unless there are adequate controls in place
                including the security of your data and other personal information.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Disclosure of Data</p>
              <p className="mt-3 text-base text-gray-600">
                Under certain circumstances, we may be required to disclose your Personal Data if required to
                do so by law or in response to valid requests by public authorities.
              </p>
              <p className="mt-3 text-base text-gray-600">
                If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal
                Data may be transferred.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Security of Data</p>
              <p className="mt-3 text-base text-gray-600">
                The security of your data is important to us but remember that no method of transmission over
                the Internet or method of electronic storage is 100% secure. While we strive to use
                commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute
                security.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">
                Your Data Protection Rights Under General Data Protection Regulation (GDPR)
              </p>
              <p className="mt-3 text-base text-gray-600">
                If you are a resident of the European Union (EU) and European Economic Area (EEA), you have
                certain data protection rights, covered by GDPR. – See more at
                https://eur-lex.europa.eu/eli/reg/2016/679/oj
              </p>
              <p className="mt-3 text-base text-gray-600">
                We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of
                your Personal Data.
              </p>
              <p className="mt-3 text-base text-gray-600">
                If you wish to be informed what Personal Data we hold about you and if you want it to be
                removed from our systems, please email us at support@timehuddle.com.
              </p>
              <p className="mt-3 text-base text-gray-600">
                Please note that we may ask you to verify your identity before responding to such requests.
                Please note, we may not able to provide Service without some necessary data.
              </p>
              <p className="mt-3 text-base text-gray-600">
                You have the right to complain to a Data Protection Authority about our collection and use of
                your Personal Data. For more information, please contact your local data protection authority
                in the European Economic Area (EEA).
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">
                Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)
              </p>
              <p className="mt-3 text-base text-gray-600">
                CalOPPA is the first state law in the nation to require commercial websites and online
                services to post a privacy policy. The law’s reach stretches well beyond California to require
                a person or company in the United States (and conceivable the world) that operates websites
                collecting personally identifiable information from California consumers to post a conspicuous
                privacy policy on its website stating exactly the information being collected and those
                individuals with whom it is being shared, and to comply with this policy. – See more at:
                https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
              </p>
              <p className="mt-3 text-base text-gray-600">Our Policy on “Do Not Track” Signals:</p>
              <p className="mt-3 text-base text-gray-600">
                We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do
                Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web
                browser to inform websites that you do not want to be tracked.
              </p>
              <p className="mt-3 text-base text-gray-600">
                You can enable or disable Do Not Track by visiting the Preferences or Settings page of your
                web browser.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">
                Your Data Protection Rights under the California Consumer Privacy Act (CCPA)
              </p>
              <p className="mt-3 text-base text-gray-600">
                If you are a California resident, you are entitled to learn what data we collect about you,
                ask to delete your data and not to sell (share) it. To exercise your data protection rights,
                you can make certain requests and ask us: What personal information we have about you. If you
                make this request, we will return to you:
              </p>
              <p className="mt-3 text-base text-gray-600">
                Please note, you are entitled to ask us to provide you with this information up to two times
                in a rolling twelve-month period. When you make this request, the information provided may be
                limited to the personal information we collected about you in the previous 12 months.
              </p>
              <p className="mt-3 text-base text-gray-600">
                To delete your personal information. If you make this request, we will delete the personal
                information we hold about you as of the date of your request from our records and direct any
                service providers to do the same. In some cases, deletion may be accomplished through
                de-identification of the information. If you choose to delete your personal information, you
                may not be able to use certain functions that require your personal information to operate.
              </p>
              <p className="mt-3 text-base text-gray-600">
                To stop selling your personal information. We don't sell or rent your personal information to
                any third parties for any purpose. You are the only owner of your Personal Data and can
                request disclosure or deletion at any time.
              </p>
              <p className="mt-3 text-base text-gray-600">
                Please note, if you ask us to delete or stop selling your data, it may impact your experience
                with us, and you may not be able to participate in certain programs or membership services
                which require the usage of your personal information to function. But in no circumstances, we
                will discriminate against you for exercising your rights.
              </p>
              <p className="mt-3 text-base text-gray-600">
                To exercise your California data protection rights described above, please send your
                request(s) by one of the following means:
              </p>
              <p className="mt-3 text-base text-gray-600">By email: support@timehuddle.com</p>
              <p className="mt-3 text-base text-gray-600">
                Your data protection rights, described above, are covered by the CCPA, short for the
                California Consumer Privacy Act. To find out more, visit the official California Legislative
                Information website. The CCPA took effect on 01/01/2020.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Service Providers</p>
              <p className="mt-3 text-base text-gray-600">
                We may employ third party companies and individuals to facilitate our Service (“Service
                Providers”), provide Service on our behalf, perform Service-related services or assist us in
                analysing how our Service is used.
              </p>
              <p className="mt-3 text-base text-gray-600">
                These third parties have access to your Personal Data only to perform these tasks on our
                behalf and are obligated not to disclose or use it for any other purpose.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Analytics</p>
              <p className="mt-3 text-base text-gray-600">
                We may use third-party Service Providers to monitor and analyze the use of our Service.
              </p>
              <p className="mt-3 text-base text-gray-600">
                These third parties have access to your Personal Data only to perform these tasks on our
                behalf and are obligated not to disclose or use it for any other purpose.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Payments</p>
              <p className="mt-3 text-base text-gray-600">
                We may provide paid products and/or services within Service. In that case, we use third-party
                services for payment processing (e.g. payment processors).
              </p>
              <p className="mt-3 text-base text-gray-600">
                We will not store or collect your payment card details. That information is provided directly
                to our third-party payment processors whose use of your personal information is governed by
                their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as
                managed by the PCI Security Standards Council, which is a joint effort of brands like Visa,
                Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure
                handling of payment information.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Changes to This Privacy Policy</p>
              <p className="mt-3 text-base text-gray-600">
                We may update our Privacy Policy from time to time. We will notify you of any changes by
                posting the new Privacy Policy on this page.
              </p>
              <p className="mt-3 text-base text-gray-600">
                We will let you know via email and/or a prominent notice on our Service, prior to the change
                becoming effective and update “effective date” at the top of this Privacy Policy.
              </p>
              <p className="mt-3 text-base text-gray-600">
                You are advised to review this Privacy Policy periodically for any changes. Changes to this
                Privacy Policy are effective when they are posted on this page.
              </p>
            </div>

            <div className="py-9">
              <p className="text-xl font-semibold text-black">Contact Us</p>
              <p className="mt-3 text-base text-gray-600">
                If you have any questions about this Privacy Policy, please contact us:
              </p>
              <p className="mt-3 text-base text-gray-600">By email: support@timehuddle.com.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
