name: PR Update

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/CODEOWNERS"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    name: Type check
    uses: ./.github/workflows/check-types.yml
    secrets: inherit

  test:
    name: Unit tests
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  lint:
    name: Linters
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  build:
    name: Production build
    uses: ./.github/workflows/production-build.yml
    secrets: inherit

  analyze:
    needs: build
    uses: ./.github/workflows/nextjs-bundle-analysis.yml
    secrets: inherit

  required:
    needs: [lint, type-check, test, build]
    if: always()
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
